### ISSUE TITLE
Request change TM_LATEX_MASTER to allow paths relative to project root

### ISSUE THREAD

**Issue by macite** [textmate/latex.tmbundle#10]
Currently TM_LATEX_MASTER requires an absolute path if LaTex files are not all located in the project root directory. This behaviour could be changed to allow relative paths with the following small alteration to determine_ts_directory.

Change determine_ts_directory in texMate.py to the following:

  def determine_ts_directory(tsDirectives):
      """Determine the proper directory to use for typesetting the current document"""
      master = os.getenv('TM_LATEX_MASTER')
      proj = os.getenv('TM_PROJECT_DIRECTORY')
    
      if proj and master:
          texfile = proj
          startDir = os.path.normpath(proj)
      else:
          texfile = os.getenv('TM_FILEPATH')
          startDir = os.path.dirname(texfile)
     ...

**Comment by sanssecours** [comment]
Hi Andrew,

sorry for the super late reply. Could you please provide steps to create a sample tex project, that shows the problem. Would setting `%!TEX root =` work in your situation?

Kind regards,
  René

**Comment by sanssecours** [comment]
Closing this for now due to a lack of response. If anyone is still interested in this feature, then please just comment below.
