### ISSUE TITLE
Watch Document+multiple source files+completion

### ISSUE THREAD

**Issue by szymtor** [textmate/latex.tmbundle#114]
I work with Watch Document (especially after it has been greatly enhanced by René).
I typically have multiple source files. It would be convenient if, in this setting, autocompletion (of citations or of labels) worked as expected, i.e., looked from the watched document, without having to define %!TEX root or TM_LATEX_MASTER.

**Comment by sanssecours** [comment]
Hi Szymon,

commit 4ccec559 adds support for the behaviour you want. Basically you need to set the environment variable `TM_LATEX_WATCH_SET_MASTER`:
<img width="592" alt="tm_latex_watch_set_master" src="https://cloud.githubusercontent.com/assets/691989/8575895/b2a39d7a-259e-11e5-9375-03c553f27d37.png">
Here is a description of the variable and the behaviour it introduces from the relevant section of the [help document][]:

> `TM_LATEX_WATCH_SET_MASTER`: If you set this variable — you can use any value you like — then “Watch Document” sets `TM_LATEX_MASTER` to the path of the watched file. For this purpose the command creates a `.tm_properties` file in the folder of the watched file. This works only if there is no such file in the folder already. If your project folder already contains a `.tm_properties` file, then you can of course still set the master file yourself. Just define the `TM_LATEX_MASTER` variable. For a description of how to do that, please just consult the section “Using the `TM_LATEX_MASTER` Environment Variable”.

Kind regards,
  René

[help document]: https://github.com/textmate/latex.tmbundle/blob/master/Support/help.markdown#environment-variables
