### ISSUE TITLE
Compiling LaTeX document fails while parsing log

### ISSUE THREAD

**Issue by janten** [textmate/latex.tmbundle#117]
Same error as described in the link below. Compiling worked fine until yesterday evening, fails now for unchanged document.

http://tex.stackexchange.com/questions/227633/strange-error-trying-to-compile-latex-document

**Comment by sanssecours** [comment]
Hi Jan-Gerd,

thanks for the bug report. Could you please provide a (minimal) sample document, so that I can reproduce the error myself.

Kind regards,
  René

**Comment by bmedinab** [comment]
Hey there, well it seems like creating that minimal sample document is harder than I thought
I'm guessing it has to do with biber.
Or \ref
I'll try tomorrow to upload a minimal document that presents this error.

**Comment by janten** [comment]
I have uploaded a minimal sample document to http://cl.ly/ZkWb?_ga=1.227835550.2017222554.1410563995

**Comment by sanssecours** [comment]
Jan-Gerd,

thank you very much for providing the minimal sample document. Commit 9dc4164e should fix the issue. Could you please check if the latest version of the bundle works for you too?

Kind regards,
  René

**Comment by janten** [comment]
Commit 9dc4164 indeed fixes the issue.
