### ISSUE TITLE
appending support path leaves lib package susceptible to namespace conflicts

### ISSUE THREAD

**Issue by aseagram** [textmate/latex.tmbundle#119]
As a Python programmer, I already have a folder called `lib` appended in my Python search path. So, when I attempt to typeset a LaTeX document from TextMate, I get an `ImportError` from `textmate.py` on  `L59`, because it is using my `lib` folder when attempting to import from `lib.tex`. Do you think that pre-pending the path (via `insert`) would be a better idea? This seems to have worked for me, for `L40`

    # sys.path.append(path.dirname(path.dirname(path.abspath(__file__))))  # noqa
    sys.path.insert(1, path.dirname(path.dirname(path.abspath(__file__))))

**Comment by sanssecours** [comment]
Hi aseagram,

thanks for the bug report and the proposed solution. The issue should be fixed in commit e2b46c4b.

Kind regards,
  René
