### ISSUE TITLE
Textmate 2 is unable to detect command mistakes in Latex

### ISSUE THREAD

**Issue by omprokash** [textmate/latex.tmbundle#120]
I am having some serious problem with Textmate 2 in Yosemite. I am typing my thesis in Latex. All of a sudden Textmate 2 stopped showing any error for undefined commands. Let me give you an example, lets say I need  to write $\alpha$, but mistakenly I typed $\apha$ in the .tex file.  When I compile it with Textmate, it does not show any error as in `Undefined Control Sequence’, it says 0 Error in the log window and just skips the part  of $\apha$ in the pdf. This is a very serious problem for me, as I am typing my thesis, I am likely to make many such typing mistakes and if these goes undetected in the compilation then that’s a huge problem for me! Could you please tell me how to solve this problem? This thing didn’t happen before, I have been using Textmate 2 in Yosemite for around 6 moths now without any problem until today. Following are codes I am using:

\documentclass[12pt]{amsart}
\usepackage{amssymb, amsmath}
\date{}

\begin{document}
\title{Error Testing}
\maketitle

I want to write $\alpha$ but mistakenly if I write $\apha$ and complie it with Textmate $2$, on the log window it does not show any error as `Undefined control sequence' and on the PDF it just skips the part where it has $\apha$. 

$\slpha$ $\alphabeta$ 
\end{document}

**Comment by sanssecours** [comment]
Hi Omprokash Das,

thanks for the bug report. The example you posted seems to work for me. I saved it under the name `bla.tex` and compiled it via “Typeset & View (PDF)”. This is the output I get:
![example](https://cloud.githubusercontent.com/assets/691989/6202969/86750962-b507-11e4-9a9c-ed90ca9d24a2.png)

As for why the example does not work for you: One possibility is that you used a filename with some special characters, that were not recognized by the regex we use to parse the log file.

Could you please try the following:

1. Rename your tex file to something simple like `bla.tex`
2. Remove the temporary files produced by the tex engine/`texmate`. One possible way to do that is to open the tex file in TextMate and then press <kbd>^⌥⌫</kbd>.
3. Translate the file with “Typeset & View (PDF)” <kbd>⌘R</kbd>.

Does this work for you?

Kind regards,
  René

**Comment by omprokash** [comment]
Hi René,
Thank you very much! It worked. It turns out that the file name was the problem, it was two ward name with a blank space in between them. Naming the .tex file as a single word and trashing all auxiliary files solved the problem.

Thank you so much, you are a life saver!

Omrpokash Das

**Comment by sanssecours** [comment]
Hi Omrpokash Das,

glad that I could help. Commit f7aab3bb should fix your problem. If you find any other non-recognized errors/warning messages in the future: Please report them too.

Kind regards,
  René

**Comment by omprokash** [comment]
Hi René,
Thanks again but what do I do with ` Commit f7aab3b <https://github.com/textmate/latex.tmbundle/commit/f7aab3bb2644e43fda800ba4db69c1933d6deca4>’? I don’t anything about coding.

Thanks,
Omprokash Das

**Comment by sanssecours** [comment]
Hi Omprokash Das,

> Thanks again but what do I do with ` Commit f7aab3b

actually you do not need to do anything. The bundle should be updated automatically sometimes in the future, after Michael (infininight) or Allan (sorbits) push out the changes. I just referenced the commit so you could check out the code that changed.

Thanks again for the bug report,
  René
