### ISSUE TITLE
Lualatex default engine

### ISSUE THREAD

**Issue by SdotVdot** [textmate/latex.tmbundle#121]
When I try to compile a document using the LuaLaTeX engine, textmate is calling Xetex instead so the document is not compiled.

The document I tried to compile is the LuaTeX.tex that comes with MacTex. 

EDIT: It is necessary to have the directive: %!TEX TS-program = lualatex
otherwise it will choose xetex

**Comment by sanssecours** [comment]
Hi S.V.,

thanks for the bug report. Could you please provide the sample file. My tex distribution seems to lack the file `LuaTeX.tex`. Both `mdfind -name LuaTeX.tex` and `locate LuaTeX.tex` give me no (useful) result.

Thanks,
  René

**Comment by SdotVdot** [comment]
\documentclass{article}
\usepackage{fontspec}
\setmainfont[Ligatures=TeX]{TeX Gyre Bonum}
\setsansfont[Ligatures=TeX,Scale=MatchLowercase]{Latin Modern Sans}
\setmonofont[Scale=MatchLowercase]{Menlo}
\begin{document}
\title{Testing in Lua\LaTeX}
\author{Testing}
\maketitle

Testing

\end{document}

**Comment by sanssecours** [comment]
Thanks for the sample file S.V.. After commit c7e796b translating this file works without setting `%!TEX TS-program = lualatex`.
