### ISSUE TITLE
Options ignored (-shell-escape)?

### ISSUE THREAD

**Issue by Reggian** [textmate/latex.tmbundle#122]
I am trying to use a package (minted) which uses 'pygmentize'. It is said that the -shell-escape flag should make things work.
When I Cmd+R I get an error:
```
...
Latex Error: ./my_file.tex:21 Package minted Error: You must have `pygmentize' installed to use this package.
...
Command pdflatex -interaction=nonstopmode -file-line-error-style -synctex=1 -shell-escape exited with status 1
...
```
although when I try the said command in terminal:
```shell
pdflatex -interaction=nonstopmode -file-line-error-style -synctex=1 -shell-escape my_file
```
the pdf is created.
I do not know if this is a tmbundle issue or a TextMate issue.

**Comment by sanssecours** [comment]
Hi Reggian,

> ... You must have `pygmentize' installed to use this package.

looks like your system lacks the `Pygments` package. One way to install it:

1. Open Terminal
2. Enter the following command:
```bash
sudo pip install -U Pygments
```
> I do not know if this is a tmbundle issue or a TextMate issue.

It should be neither :). The following code saved under the name `tmp.tex` works without problems for me:

```latex
\documentclass{article}
\usepackage{minted}

\begin{document}
\begin{minted}[mathescape,
               linenos,
               numbersep=5pt,
               gobble=2,
               frame=lines,
               framesep=2mm]{csharp}
  string title = "This is a Unicode π in the sky"
  /*
  Defined as $\pi=\lim_{n\to\infty}\frac{P_n}{d}$ where $P$ is the perimeter
  of an $n$-sided regular polygon circumscribing a
  circle of diameter $d$.
  */
  const double pi = 3.1415926535
\end{minted}
\end{document}
```

Kind regards,
  René

**Comment by Reggian** [comment]
Hi René,

thank you for your swift comment, but I have the Pygments installed.
Typing:
```shell
pygmentize -V
```
 into Terminal retunrns:
```
Pygments version 2.0.2, (c) 2006-2014 by Georg Brandl.
```

Or am I missing something?
Cheers,
R.

**Comment by sanssecours** [comment]
Hi Reggian,

maybe your TextMate `PATH` does not contain the path to `pygmentize`? Can you please try the following:

1. Open TextMate
2. Create a new file: <kbd>⌘N</kbd>
3. Paste the following command: `pygmentize -V`
4. Press <kbd>^R</kbd>

If this works correctly then your new document should show the following in line 2: `Pygments version 2.0.2, (c) 2006-2014 by Georg Brandl.`

Kind regards,
  René

**Comment by Reggian** [comment]
Hi René,

I have done as instructed and I got the following error:

	Failure running “Execute Line”.
	/bin/bash: line 1: pygmentize: command not found

The `PATH` variable contains `$PATH:/opt/local/bin:/usr/local/bin:/usr/texbin` and I have confirmed that `pygmentize` is located in `/usr/local/bin`.

Thank you for helping out.

Cheers,
R.

**Comment by sanssecours** [comment]
Hi Reggian,

> I have done as instructed and I got the following error:...

strange. Maybe the checkbox left to the variable `PATH` is unchecked. Can you please do the following to check the content of `PATH`:

1. Open TextMate
2. Create a new file: <kbd>⌘N</kbd>
3. Paste the following command: `echo $PATH`
4. Press <kbd>^R</kbd>

Does the result contain `/usr/local/bin`?

Kind regards,
  René

**Comment by Reggian** [comment]
AHA!!
There it was. I had to check the checkbox.
Thank you so much for your help and sorry for spamming your issue tracker.
Cheers,
R.
