### ISSUE TITLE
Add support for TEX root directive to “Watch Document”

### ISSUE THREAD

**Issue by sanssecours** [textmate/latex.tmbundle#123]
Support for “!TEX root = ” should fix this issue reported to the [mailing list](http://textmate.1073791.n5.nabble.com/Watch-Document-in-TeX-project-with-multiple-documents-td29057.html):

> The Watch Document command (Cmd-Ctrl-W) in the LaTeX bundle works beautifully either for a single TeX document or for a series of documents if started from the master file. Is it possible to tweak Watch Document so it can be called from any of these sub-files that are linked to the master?

**Comment by gildasius** [comment]
I am still interested in this feature and wonder if it is implementable? Amicalement, --Gildas Hamel

**Comment by sanssecours** [comment]
Hi Gildas,

> I am still interested in this feature and wonder if it is implementable?

yes — I will look into it in the next days. 

Kind regards,
  René

**Comment by sanssecours** [comment]
Hi again,

commit bd56dcca adds support for `%!TEX root` directives. To set a master file just add:

```tex
%!TEX root = path_to_master
```

in the first 20 lines of your tex file. You can also use the command “Set Master File” to do that.

Kind regards,
  René

**Comment by gildasius** [comment]
* Skriv a reas René Schwaiger (notifications@github.com):

  |>  commit bd56dcca adds support for `%!TEX root` directives. To set a master file just add:
  |>  
  |>  ```tex
  |>  %!TEX root = path_to_master
  |>  ```
  |>  
  |>  in the first 20 lines of your tex file. You can also use the command “Set Master File” to do that.

It works great, thank you. --gildas
