### ISSUE TITLE
separate formatting for text within a footnote

### ISSUE THREAD

**Issue by amroberts1** [textmate/latex.tmbundle#124]
I use XeLaTeX to write academic history, and so my documents make much use of the `\footnote{...}` command. (In case it is relevant, I should note that in my documents these footnotes often make use of non-Latin scripts, in particular Greek and Arabic.) It would therefore be a great help to me if the text within footnotes were formatted in TextMate differently from normal text, for example with a smaller font size or a highlighted background. This would make it easier, when looking at a paragraph, to visually distinguish between the main text and footnotes. As a MWE, here is an example paragraph:

```
This sentence makes an argument.\footnote{This footnote substantiates the argument by referencing Author, \emph{Title}, 65.}
This sentence quotes a text in my English translation which reads, ``Know yourself!"\footnote{This footnote contains the quote in the original language: ``\emph{gnōthi seauton}."}
```

(I would usually use `fontspec` in order to print the Greek in a Greek Unicode font -- `\greek{γνῶθι σεαυτόν}` -- but omit that here for simplicity.)

**Comment by sorbits** [comment]
I think this suggestion is more appropriate to implement in 
https://github.com/bcomnes/LaTeX-Font-Settings.tmbundle which can be 
installed from Preferences → Bundles.

**Comment by amroberts1** [comment]
OK, thanks! I just [posted](https://github.com/bcomnes/LaTeX-Font-Settings.tmbundle/issues/5) it there.

**Comment by sanssecours** [comment]
Hi,

just created a [pull request](https://github.com/bcomnes/LaTeX-Font-Settings.tmbundle/pull/6) at the repo mentioned by Allan. @amroberts1 If you have any styling suggestions — font, size, etc. — then please comment under the pull request.

Kind regards,
  René
