### ISSUE TITLE
Making a contribution to the latex.tmbundle repository for nomencl LaTeX package

### ISSUE THREAD

**Issue by WillemJacobus** [textmate/latex.tmbundle#126]
Hi 

I have made modifications to the texmate.py script so that it create an index for the LaTeX package nomencl (nomenclature). I'm new to GitHub, so I don't know how to submit a contribution to this repository. Could anyone give me instructions of how to do it?

Willem

**Comment by sanssecours** [comment]
Hi Willem,

> I'm new to GitHub, so I don't know how to submit a contribution to this repository. Could anyone give me instructions of how to do it?

basically you start by creating one or more commits. After that you create a pull request. The people at GitHub put a nice documentation covering this process [here](https://help.github.com/articles/using-pull-requests).

> I have made modifications to the texmate.py script so that it create an index for the LaTeX package nomencl (nomenclature).

Commit 6a68efa0 extends the bundle's `latexmk` file with a rule covering the process of creating a nomenclature. This means that “Typeset & View (PDF)” will now automatically create a nomenclature if you checked “Use Latexmk” inside the bundle preferences. This should — at least in theory — more or less cover the changes you mentioned.

Kind regards,
  René

**Comment by WillemJacobus** [comment]
Hi René

Thank you for the response. I was not aware of latexmk, and with commit 6a68efa the issue seems to be fixed, which is wonderful. I guess the commit 6a68efa will be available in the next update of the LaTeX Texmate bundle?

W

W

**Comment by sanssecours** [comment]
>  I guess the commit 6a68efa will be available in the next update of the LaTeX Texmate bundle?

Yes, the official bundle will be updated after Michael (infininight) or Allan (sorbits) find time to deploy the changes.
