### ISSUE TITLE
Issue with latex_watch.pl

### ISSUE THREAD

**Issue by masonlr** [textmate/latex.tmbundle#130]
Hi, I think these lines are causing issues with latex_watch.pl on my mac (https://github.com/textmate/latex.tmbundle/blob/master/Support/bin/latex_watch.pl#L303-L304):
       
        remove_tree( "$wd/pythontex-files-" . $name =~ s/ /-/gr );
        remove_tree( "$wd/_minted-" . $name =~ s/ /-/gr );

"Watch document" hangs with a cocoa dialogue box unless I change them so something similar to              

        (my $name_tmp = $name) =~ s/ /-/;
        remove_tree( "$wd/pythontex-files-" . $name_tmp );
        remove_tree( "$wd/_minted-" . $name_tmp );

**Comment by sanssecours** [comment]
Hi masonlr,

thank you for the bug report. Commit a20438e8 should fix your issue. If the problem remains, then please comment below.

Kind regards,
  René
