### ISSUE TITLE
latex dvips ps2pdf

### ISSUE THREAD

**Issue by jonso99** [textmate/latex.tmbundle#131]
Hi
In the latest version the latex workflow (latex dvips ps2pdf) is broken, it seems to call pdflatex and then it will not compile any document that has eps figures or pstricks commands.

**Comment by sanssecours** [comment]
Hi jonso99,

thank you for your bug report. The following document:

```latex
\documentclass{article}

\usepackage{graphicx}

\begin{document}

\begin{figure}[htbp]
  \centering
    \includegraphics[width=\textwidth]{/usr/share/emacs/22.1/etc/gnus-logo.eps}
  \caption{Blubb}
  \label{fig:label}
\end{figure}

\end{document}
```
translates fine for me. I saved the file under the name `tmp.tex`, set the engine to `latex` and used “Typeset & View (PDF)”. Does this example work for you? If yes, could you please provide a (minimal) sample project that does not work? 

One thing I can think of that might be a problem is the cache file (`.lb`) the command produces. Could try to run “Clean” (<kbd>^</kbd> + <kbd>⌥</kbd> + <kbd>⌫</kbd>) before you re-translate your file? That might fix your problem.

Kind regards,
  René

**Comment by jonso99** [comment]
Hi

Thanks.

I got it to work.  first tried pulling from git and reverting to an
older version of the bundle. That did not work either but gave me the
error message that ps2pdf could not be found. And adjusting the PATH
in textmate fixed it. 

This is on a new mac with textmate2 and latex installed 2 weeks ago,
so looks like a problem in how textmate was (then) distributed. I just
tried on my old mac and it worked fine there. 

quite possibly along the way the cache file (.lb) got deleted also,
which may then have fixed the problem. 

thanks again, and it is a great package which I use all the time.

j

On 01/08/2015 at 3:22 PM, "René Schwaiger"  wrote:

	Hi jonso99, 

	thank you for your bug report. The following document: 

	documentclass{article} usepackage{graphicx} begin{document}
begin{figure}[htbp]   centering    
includegraphics[width=textwidth]{/usr/share/emacs/22.1/etc/gnus-logo.eps}
  caption{Blubb}   label{fig:label} end{figure} end{document} 

	translates fine for me. I saved the file under the name tmp.tex, set
the engine to latex and used “Typeset & View (PDF)”. Does this
example work for you? If yes, could you please provide a (minimal)
sample project that does not work?  

	One thing I can think of that might be a problem is the cache file
(.lb) the command produces. Could try to run “Clean” (^ + ⌥ +
⌫) before you re-translate your file? That might fix your problem. 

	Kind regards,
   René
