### ISSUE TITLE
Watch Document (Ctrl-Cmd-W) hangs,  worked two days ago 

### ISSUE THREAD

**Issue by Bilalh** [textmate/latex.tmbundle#132]
Watch Document {ctrl-cmd-w} just hangs now,  worked two days ago (i.e. 17th August).   The progress bar with title 'Latex Watch' is shown and hangs.

<img width="495" alt="screen shot 2015-08-19 at 17 51 00" src="https://cloud.githubusercontent.com/assets/171602/9362858/e2c72dec-469a-11e5-9dc6-7ec2b2c2eac9.png">

Typeset & View (PDF) {cmd-r} still works.  I tried many latex document, this results in the same error when using `Watch Document`.

```
TextMate version 2.0-beta.7.4
OS X 10.10.5 (14F27)
```

**Comment by sanssecours** [comment]
Hi Bilal,

thank you for the bug report. The command still works for me. Could you please specify a document that does not work for you? For example, if you save the following code:
```tex
\documentclass{article}
\begin{document}
Blubb
\end{document}
```
in a file called `tmp.tex` and invoke “Wach Document”: Does the command freeze? Which typesetting engine do you use (pdflatex, xelatex, lualatex,…)?

Thanks,
  René

By the way: As temporary workaround, you can download an old version of the bundle [here](https://github.com/textmate/latex.tmbundle/releases/download/v1.0.0/LaTeX.tmbundle.zip).

**Comment by Bilalh** [comment]
After 2 minutes, still not loaded. 

<img width="1440" alt="screen shot 2015-08-19 at 21 03 24" src="https://cloud.githubusercontent.com/assets/171602/9367534/cb63613c-46b5-11e5-8c05-572c176ece2d.png">

Looking at Activity Monitor,  Textmate is at %0  the dialog at 5% and there is no latex like processes

<img width="832" alt="screen shot 2015-08-19 at 21 05 17" src="https://cloud.githubusercontent.com/assets/171602/9367561/039f00ec-46b6-11e5-91b3-be4b8b2680c2.png">
<img width="832" alt="screen shot 2015-08-19 at 21 05 11" src="https://cloud.githubusercontent.com/assets/171602/9367562/03c3f82a-46b6-11e5-88d4-47aa6399afba.png">

Oddly the dialog still keep on running even after text mate has been closed.



For information, my latex setting are:

<img width="492" alt="screen shot 2015-08-19 at 21 11 26" src="https://cloud.githubusercontent.com/assets/171602/9367688/e661443a-46b6-11e5-8900-67a3b1cc0c20.png">


Another oddity is that   typeset & View (PDF) {cmd-r} works instantly  but give an error  message at the end.

````
This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2014) (preloaded format=pdflatex

Processing: test.tex

Document Class: article 2007/10/19 v1.4h Standard LaTeX document class

Output written on test.pdf (1 page, 10786 bytes).

Complete transcript is in test.log

/bin/sh: mate: command not found
````

**Comment by szymtor** [comment]
I have the same problem, on two different computers. Worked fine yesterday.

**Comment by sanssecours** [comment]
> `/bin/sh: mate: command not found`

You need to install `mate` inside `Preferences→Terminal` to get rid of this message.

In the moment I assume that Perl on OS X does not include a YAML library by default. Maybe I installed one by mistake…

Can you (or Szymon) please try the following:

1. Install the Perl bundle
2. Create a new file
3. Paste the following code:
    ```perl
    use strict;
    use warnings;

    use YAML qw(LoadFile);

    print 'Blubb'
    ``` 
4. Save the file as `tmp.pl`
5. Invoke “Run” (<kbd>⌘</kbd>  + <kbd>R</kbd>)

The output of the command should just be: `Blubb`

If that worked, can you then please do the following:

1. Download this [debug version of the bundle](https://github.com/textmate/latex.tmbundle/releases/download/v1.1.0test1/LaTeX.tmbundle.zip)
2. Put the bundle into `~/Library/Application\ Support/Avian/Bundles/LaTeX.tmbundle/`
3. Restart TextMate
4. Install the `Make` bundle inside `Preferences`
5. Open the `Makefile` included in the bundle e.g. by using this command in the Terminal
```bash
mate ~/Library/Application\ Support/Avian/Bundles/LaTeX.tmbundle/Makefile 
```
6. Invoke the command `Build` (<kbd>⌘</kbd>+<kbd>B</kbd>)
7. Paste the output of the command show in the HTML output window

**Comment by Bilalh** [comment]
Running the perl gives an error message about missing YAML

````
Running “tmp.pl”…
Perl v5.18.2
Theme:  
Can't locate YAML.pm in @INC (you may need to install the YAML module) (@INC contains: /Users/bilalh/Library/Application Support/TextMate/Managed/Bundles/Perl.tmbundle/Support /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /Users/bilalh/Desktop/tmp.pl line 4.
BEGIN failed--compilation aborted at /Users/bilalh/Desktop/tmp.pl line 4.

exception_handler::die	 in tmp.pl at line 4
copy outputProgram exited with code #0 after 0.04 seconds.
```


n.b. I had mate in ~/bin,  putting it /usr/local/bin got rid of the error message in typeset & View (PDF) {cmd-r}

**Comment by sanssecours** [comment]
> Running the perl gives an error message about missing YAML

Thanks for the help. The issue should be fixed in commit 6358337b. If you want to try it right now: You can download the newest version of the bundle [here](https://github.com/textmate/latex.tmbundle/releases/tag/v1.1.1).

**Comment by szymtor** [comment]
Thanks Rene, now it's working again.

Szymon

**Comment by Bilalh** [comment]
Works for me as well
