### ISSUE TITLE
TeXCount File not found or not readable error

### ISSUE THREAD

**Issue by samfearn** [textmate/latex.tmbundle#134]
Hey,

TeXCount currently seems to be broken. Every time I try to call it the tooltip gives me an error per word in the title, as if something isn't being wrapped in quotes properly but I couldn't seem to fix it myself. I presume the two lines

    DIRECTORY=$(dirname "${TM_FILEPATH}")
    FILENAME=$(basename "${TM_FILEPATH}")

are to blame. As an explicit example, on the file 'Evaluation Claim.tex' I get 4 errors on the tooltip,

* File not found or not readable: Evaluation
* File not found or not readable: Claim.tex
* File not found or not readable: Evaluation
* File not found or not readable: Claim.tex

**Comment by sanssecours** [comment]
Hi Sam,

could you please provide a minimal non-working example? I saved the following code:
```tex
\documentclass{article}

\begin{document}
 One Two Three
\end{document}
```
in a file called `Evaluation Claim.tex`. After I invoked the command I get the following (correct) output:
<img width="233" alt="texcount" src="https://cloud.githubusercontent.com/assets/691989/10107043/9d3254ec-63b8-11e5-85ab-e2aa1e9e476e.png">

By the way, it is also possible that this is an error in [TeXcount](http://app.uio.no/ifi/texcount/) itself. Did you try `texcount` in the command line?

Kind regards,
  René

**Comment by samfearn** [comment]
It seems to be simply a problem when the filename is multiple words with a space. If I save your MWE with the name 'test test.tex' then run texcount from the bundle I get the same error, but on a file with a single word filename the command runs fine. The texcount script is obviously not properly capturing the name in quotes.

**Comment by sanssecours** [comment]
Unfortunately I still can not reproduce your error. Even if I name the file `test test.tex` and save it in a folder called `hu hu hu`, the command still works fine:
<img width="233" alt="test test" src="https://cloud.githubusercontent.com/assets/691989/10107557/4113e096-63bc-11e5-9cda-8fbd508168f2.png">

Did you maybe modify something in the bundle? If so, then there should be another `latex.tmbundle` somewhere on you drive, most likely in the folder `~/Library/Application\ Support/Avian/Bundles/`. You can check for multiple versions of the LaTeX Bundle by entering the following command in Terminal:
```bash
mdfind latex.tmbundle
``` 
Could you please post a screenshot of the error output “TeXcount” displays, when you invoke the command on the file `test test.tex`?

**Comment by samfearn** [comment]
It's entirely possible I've modified something whilst trying to fix the odd problem I've had before. I do indeed have a latex.tmbundle in the folder you said.

Here's a screenshot of what happens when I try to run texcount on 'test test.tex'

![screenshot](https://cloud.githubusercontent.com/assets/2106074/10108173/5894116e-63b7-11e5-84e4-37cb088361b7.jpg)

**Comment by sanssecours** [comment]
> I do indeed have a latex.tmbundle in the folder you said. 

Could you please move the LaTeX bundle in said folder (temporarily) into the Trash. After that please restart TextMate (<kbd>^</kbd>+<kbd>⌘</kbd>+<kbd>Q</kbd>) and try again. Does the command still display the same error message after that?

**Comment by samfearn** [comment]
Ok, I tried that, but I get exactly the same error.

**Comment by sanssecours** [comment]
Do you still have other copies of the bundle lying somewhere around? Please enter the following command into Terminal – located inside the folder `/Applications/Utilities/Terminal`:

```bash
mdfind latex.tmbundle
```
What is the output of the command? Please move every bundle the command shows – except the one in `~/Library/Application Support/TextMate/Managed/Bundles` – into the Trash and try again after you restarted TextMate. Does the problem persist?

**Comment by samfearn** [comment]
Ok so I had copies in ~/Library/Application Support/TextMate/Managed/Bundles/, ~/Library/Application Support/TextMate/Bundles/ which I renamed. the mdfind command also found matches in ~/Library/Caches/Metadata/Safari/History/ and ~/Library/Mail/V2/ which I left as neither of these were .bundles.

I then restarted and it still had no effect.

**Comment by samfearn** [comment]
This is the contents of the TeXCount bundle item by the way

    #!/usr/bin/env bash
    [[ -f "${TM_SUPPORT_PATH}/lib/bash_init.sh" ]] && \
    . "${TM_SUPPORT_PATH}/lib/bash_init.sh"
    
    DIRECTORY=$(dirname "${TM_FILEPATH}")
    FILENAME=$(basename "${TM_FILEPATH}")
    OPTIONS=($TM_TEXCOUNT_OPTIONS)
    cd "$DIRECTORY"
    
    texcount -nocol -utf8 -inc "${OPTIONS[@]}" "$FILENAME"

**Comment by sanssecours** [comment]
> Ok so I had copies in ~/Library/Application Support/TextMate/Managed/Bundles/, ~/Library/Application Support/TextMate/Bundles/ which I renamed.

Please just leave the copy in `~/Library/Application Support/TextMate/Managed/Bundles` like it is.

Could you please also put the other LaTeX bundles into the Trash. If you only rename them, TextMate might still load them. For example, even if I rename my only copy of the bundle from `LaTeX.tmbundle` to `Please Do not Load Me.Not a tmbundle Ha Ha` in Finder, then Finder really renames the  bundle to `Please Do not Load Me.Not a tmbundle Ha Ha.tmbundle` and hides the extension. TextMate still loads this renamed copy just fine.

The content of the command you posted looks fine by the way.  You could also try to  [revert to defaults](https://github.com/textmate/textmate/wiki/Reverting-To-Defaults). Maybe this will solve your problem. I am still puzzled by what is causing this issue for you though :(. Did you already try `texcount` on a file whose name contains spaces inside Terminal?

**Comment by samfearn** [comment]
Ok, I put the file you mentioned back to how it started, moved the other files to trash and then restarted but still no joy.

I'd rather not revert to defaults as I've had to tweak some other bundles before to fix other problems, and obviously I'd lose this if I followed the revert to defaults instructions.

How do I check where the copy of texcount that the bundle calls is located? I found a copy in /usr/local/texlive/2011/texmf-dist/scripts/texcount/texcount.pl and got the following

    my computer:Claims sam$ /usr/local/texlive/2011/texmf-dist/scripts/texcount/texcount.pl "~/Desktop/test test.tex"
    File not found or not readable: /Users/sam/Desktop/test
    File not found or not readable: /Users/sam/Desktop/test
    File not found or not readable: test.tex
    File not found or not readable: test.tex

**Comment by sanssecours** [comment]
> How do I check where the copy of texcount that the bundle calls is located?

Sorry for the late answer. I went to bed after I posted my latest reply. You can locate a certain command  with the command `which`:
```sh
which texcount
```
It looks like you have a very old version of MacTeX on your computer. Upgrading to [MacTex 2015](https://www.tug.org/mactex/mactex-download.html) should solve your problem. After you upgraded, you can remove the old version by following the uninstall instructions on the [MacTeX page](https://www.tug.org/mactex/uninstalling.html).

**Comment by samfearn** [comment]
Hi René,

No need to apologise, I don't expect immediate responses late on Friday night :) or anytime for that matter, so thanks for all the quick responses so far.

The problem is that texcount doesn't seem to be in my PATH, so 'which texcount' returns nothing.

I'm updating MacTex now, I guess I stupidly never thought about the fact that this wouldn't just be auto-updating. I'll let you know whether that fixes the problem.

**Comment by samfearn** [comment]
Hey René,

So I've updated MacTeX as you suggested and it now works fine. Thanks so much for your support, particularly since this turned out not to be an issue with the Textmate bundle after all. I think I must have assumed it was since I'd used texcount like this before, but it must just have happened to be on a file with a single word title.

Anyway, thanks again.

**Comment by sanssecours** [comment]
Hi Sam,

> The problem is that texcount doesn't seem to be in my PATH, so 'which texcount' returns nothing.

since `texcount` – more or less – works for you inside TextMate it is accessible via `PATH` there. So you could also write down the command  `which texcount` in an otherwise empty line of a (LaTeX) document and press <kbd>^</kbd>+<kbd>R</kbd> while the caret is still located on the same line as the command. After you press the key combination TextMate will print the output of the command below the text `which texcount`.  

> Anyway, thanks again.

You're welcome.

Kind regards,
  René
