### ISSUE TITLE
Two alternate chapter/section names with memoir

### ISSUE THREAD

**Issue by alxh** [textmate/latex.tmbundle#136]
Hi all,

The memoir class supports two alternate names for chapters and sections etc., to use for the TOC and headers, like:

    \chapter[toc-name][header-name]{long-name}

whereas standard LaTeX supports only one:

    \chapter[toc-and-header-name]{long-name}

Would it be possible to integrate this into the LaTeX Memoir language definition file in the tmBundle? It would be very helpful if it was recognized properly, especially for quick navigation in the document.

Thanks very much in advance!

**Comment by sanssecours** [comment]
Hi Alexandre,

thank you for the well written feature request. Commit 6bc07c08 should fix your issue. If you have any additional remarks or questions, then please just comment below.

Kind regards,
  René

**Comment by alxh** [comment]
Hi René,
Thank you so much !
And happy new year :)
Regards,

Alexandre
