### ISSUE TITLE
Support for SageTex

### ISSUE THREAD

**Issue by dagola** [textmate/latex.tmbundle#137]
Hi,

I'm using SageMath commands quite often in my LaTeX documents. Following the instructions from https://github.com/dandrake/sagetex/wiki I'm able to use latexmk to compile my documents in one run. Now I would like to achieve this out of textmate using this bundle.
Unfortunately, I can't manage to getting it working. Adding the lines from the .latexmkrc in my home directory to the latexmkrc buried in this bundle results in a infinity loop of the typesetting after hitting `CMD+R`.

Any suggestions how to accomplish this?

Greetings

**Comment by sanssecours** [comment]
Hi dagola,

the procedure outlined in https://github.com/dandrake/sagetex/wiki did not work for me with the latest version of Sage (6.10). However the following worked:

1. Create a new file in TextMate
2. Paste the content of [sagetex_latexmkrc](http://tug.ctan.org/support/latexmk/example_rcfiles/sagetex_latexmkrc) into the document
3. Save the file as `.latexmkrc` in the top level of your home directory (`~/.latexmkrc`)

After the last step `latexmk` translates the file specified [here](http://doc.sagemath.org/html/en/tutorial/sagetex.html#an-example) both in the shell and TextMate without any problems. You do not need to change the `latexmkrc` file in the bundle. I would strongly recommend to not touch this file at all! `latexmk` will always load the file `~/.latexmkrc` in addition to the one specified in the bundle anyway.

Hope this helps. If you have any additional questions then please just ask below.

Kind regards,
  René

**Comment by dagola** [comment]
Hi René,

thanks for your reply!

I followed your suggestions, so the `latexmkrc` file in the bundle is the original one and `~/.latexmkrc`contains the content of the linked file.
Running in the shell `latexmk -pdf st_example.tex` results in the correct pdf: [st_example.pdf](https://github.com/textmate/latex.tmbundle/files/82300/st_example.pdf). But removing all files but `st_example.tex`, open it in TextMate and hit `CMD+R` results in an incomplete pdf: 
[st_example.pdf](https://github.com/textmate/latex.tmbundle/files/82351/st_example.pdf). 
In the typesetting window I get the following output:
```
Typesetting “st_example.tex”…
pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015) /Users/DGola/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle/Support/shared/lib/tm/process.rb:122: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777 teaser
Theme:  
/Users/DGola/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle/Support/shared/lib/tm/process.rb:122: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777
Latexmk: This is Latexmk, John Collins, 5 February 2015, version: 4.43a.

Latexmk: applying rule 'pdflatex'...

This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015) (preloaded format=pdflatex

Processing: st_example.tex
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class

LaTeX Warning: Reference `@sageinline0' on page 1 undefined on input line 8.

LaTeX Warning: Reference `@sageinline1' on page 1 undefined on input line 21.

LaTeX Warning: Reference `@sageinline2' on page 1 undefined on input line 22.

LaTeX Warning: There were undefined references.

Output written on st_example.pdf (1 page, 60373 bytes).

Complete transcript is in st_example.log

Latexmk: Log file says output to 'st_example.pdf'

Latexmk: List of undefined refs and citations:

Latexmk: Summary of warnings:

Found 0 errors, and 4 warnings in this run

Latexmk: applying rule 'cusdep sage sout st_example.sagetex'...

Latexmk: Errors, in force_mode: so I tried finishing targets

Command latexmk -pdf -f -r /tmp/latexmkrc -r '/Users/DGola/Library/Application Support/TextMate/Managed/Bundles/LaTeX.tmbundle/Support/config/latexmkrc' st_example.tex exited with status 12
```
So, it looks like the sage rule from `~/.latexmkrc` is applied but results in some error(s). I copied the `latexmkrc` file from the bundle to `/tmp` and ran the command `latexmk -pdf -f -r /tmp/latexmkrc -r '/Users/DGola/Library/Application Support/TextMate/Managed/Bundles/LaTeX.tmbundle/Support/config/latexmkrc' st_example.tex` directly from the shell (bash and zsh) with no error(s) and the correct pdf output.

I don't know how to track the error(s) generated by the TextMate latexmk run, so I'm a bit lost here. 

Maybe, you have some ideas?

Damian

**Comment by sanssecours** [comment]
Hi Damian,

first I would fix the warnings about the “insecure world writeable”. According to an article on [StackOverflow](http://stackoverflow.com/questions/3952243/warning-insecure-world-writable-dir-usr-local-bin-in-path-mode-040777) the following Terminal command, which removes write access for “group” and “others” from `usr/local/bin` should help:

```bash
sudo chmod go-w /usr/local/bin
```

After you fixed that, please remove any modification to the LaTeX bundle. For that, uninstall the bundle inside Preferences and remove every bundle that shows up after you entered the following command inside a shell or via “Execute Line” inside TextMate (`^` + R).

```
mdfind -name latex.tmbundle | grep -E '\.tmbundle$'
```

After you did that, please quit TextMate, reinstall the LaTeX bundle and check if it works now. If it does not, then please publish the content of your `~/.latexmkrc` and a screenshot of your bundle preferences (`Bundles`→`LaTeX`→`Preferences`) here. Thank you.

> So, it looks like the sage rule from ~/.latexmkrc is applied but results in some error(s). I copied the latexmkrc file from the bundle to /tmp and ran the command latexmk -pdf -f -r /tmp/latexmkrc -r '/Users/DGola/Library/Application Support/TextMate/Managed/Bundles/LaTeX.tmbundle/Support/config/latexmkrc' st_example.tex directly from the shell (bash and zsh) with no error(s) and the correct pdf output.

Actually the `latexmkrc` file in `/tmp` that “Typeset & View (PDF)” uses, is different to the one in the bundle. Otherwise it would not make sense to load them both at once. `/tmp/latexmkrc` is generated by `texmate` and looks something like this:

```perl
$latex = 'latex -interaction=nonstopmode -file-line-error-style {0}';
$pdflatex = '{1} -interaction=nonstopmode -file-line-error-style {0}'
```
where `{1}` is the engine used to translate the file (e.g. `pdflatex`) and `{0}` is a placeholder for the engine options (e.g. `-shell-escape`).

**Comment by dagola** [comment]
Thanks again for your effort.

I uninstalled the bundle via TextMate preferences

![uninstallpref](https://cloud.githubusercontent.com/assets/8808193/12195104/1fa44e06-b5f5-11e5-9982-1561c3ebc10f.png)

checked the installed bundles in the shell (nothing showed up)

![uninstallshell](https://cloud.githubusercontent.com/assets/8808193/12195124/3fe7c53a-b5f5-11e5-8517-b18920df6f40.png)

quit TextMate, reopend it and installed the LaTeX bundle again

![installpref](https://cloud.githubusercontent.com/assets/8808193/12195141/5fa7b420-b5f5-11e5-902b-772077891eb7.png)

but it still does not work

![typesetting](https://cloud.githubusercontent.com/assets/8808193/12195153/70a81aee-b5f5-11e5-86c7-35328ba85943.png)


My `~/.latexmkrc`:

![latexmkrc](https://cloud.githubusercontent.com/assets/8808193/12195160/87d63a8e-b5f5-11e5-8a01-945e4db99a9f.png)

My bundle preferences:

![bundlepref](https://cloud.githubusercontent.com/assets/8808193/12195229/f040a244-b5f5-11e5-87af-7fd5635b8f11.png)

sage works:

![sage](https://cloud.githubusercontent.com/assets/8808193/12195287/54134da8-b5f6-11e5-9e6e-eb38112d42a0.png)

**Comment by dagola** [comment]
Finally, I was able to resolve this issue. Checking `Verbose TeX output` in the bundle preferences revealed, that there was some error with the `SAGE_ROOT` variable:

```
header
Typesetting “st_example.tex”…
pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015) teaser
Theme:  
Rule 'pdflatex': Rules & subrules not known to be previously run:

pdflatex

Rule 'pdflatex': The following rules & subrules became out-of-date:

'pdflatex'

------------

------------

------------

Running 'pdflatex -interaction=nonstopmode -file-line-error-style -interaction=nonstopmode -file-line-error-style -synctex=1 -shell-escape -recorder "st_example.tex"'

------------

This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015) (preloaded format=pdflatex

\write18 enabled.

entering extended mode

Processing: st_example.tex
LaTeX2e <2015/10/01> patch level 2

Babel <3.9m> and hyphenation patterns for 79 languages loaded.

(/usr/local/texlive/2015/texmf-dist/tex/latex/base/article.cls

Document Class: article 2014/09/29 v1.4h Standard LaTeX document class

(/usr/local/texlive/2015/texmf-dist/tex/latex/base/size10.clo))

(/Users/DGola/Library/texmf/tex/generic/sagetex/sagetex.sty

(/usr/local/texlive/2015/texmf-dist/tex/latex/tools/verbatim.sty)

(/usr/local/texlive/2015/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty

Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix <2008/02/07> (tvz)

(/usr/local/texlive/2015/texmf-dist/tex/latex/graphics/keyval.sty))

(/usr/local/texlive/2015/texmf-dist/tex/latex/listings/listings.sty

(/usr/local/texlive/2015/texmf-dist/tex/latex/listings/lstmisc.sty)

(/usr/local/texlive/2015/texmf-dist/tex/latex/listings/listings.cfg))

(/usr/local/texlive/2015/texmf-dist/tex/latex/graphics/color.sty

(/usr/local/texlive/2015/texmf-dist/tex/latex/latexconfig/color.cfg)

(/usr/local/texlive/2015/texmf-dist/tex/latex/pdftex-def/pdftex.def

(/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/infwarerr.sty)

(/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/ltxcmds.sty)))

(/usr/local/texlive/2015/texmf-dist/tex/latex/graphics/graphicx.sty

(/usr/local/texlive/2015/texmf-dist/tex/latex/graphics/graphics.sty

(/usr/local/texlive/2015/texmf-dist/tex/latex/graphics/trig.sty)

(/usr/local/texlive/2015/texmf-dist/tex/latex/latexconfig/graphics.cfg)))

(/usr/local/texlive/2015/texmf-dist/tex/latex/makecmds/makecmds.sty)

(/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/ifpdf.sty)

(/usr/local/texlive/2015/texmf-dist/tex/latex/base/ifthen.sty)

(/usr/local/texlive/2015/texmf-dist/tex/generic/ifxetex/ifxetex.sty)

No file st_example.sagetex.sout.

) (./st_example.aux)

(/usr/local/texlive/2015/texmf-dist/tex/context/base/supp-pdf.mkii

[Loading MPS to PDF converter (version 2006.09.02).]

) (/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/pdftexcmds.sty

(/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/ifluatex.sty))

(/usr/local/texlive/2015/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty

(/usr/local/texlive/2015/texmf-dist/tex/latex/oberdiek/grfext.sty

(/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/kvdefinekeys.sty))

(/usr/local/texlive/2015/texmf-dist/tex/latex/oberdiek/kvoptions.sty

(/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty

(/usr/local/texlive/2015/texmf-dist/tex/generic/oberdiek/etexcmds.sty)))

(/usr/local/texlive/2015/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))

LaTeX Warning: Reference `@sageinline0' on page 1 undefined on input line 8.

LaTeX Warning: Reference `@sageinline1' on page 1 undefined on input line 21.

LaTeX Warning: Reference `@sageinline2' on page 1 undefined on input line 22.

Package sagetex Warning: Graphics file sage-plots-for-st_example.tex/plot-0.pdf on page 1 does not exist. Plot command is on input line 27.

*********************************************************************

Package sagetex Warning: there were undefined Sage formulas and/or plots.

Run Sage on st_example.sagetex.sage, and then run LaTeX on st_example.tex again.

*********************************************************************

[1{/usr/local/texlive/2015/texmf-var/fonts/map/pdftex/updmap/pdftex.map}]

(./st_example.aux)

LaTeX Warning: There were undefined references.

)

Output written on st_example.pdf (1 page, 60373 bytes).

SyncTeX written on st_example.synctex.gz.

Complete transcript is in st_example.log

'No file st_example.sagetex.sout.'

Reference `@sageinline0' on page 1 undefined on input line 8

Reference `@sageinline1' on page 1 undefined on input line 21

Reference `@sageinline2' on page 1 undefined on input line 22

Latex failed to resolve 3 reference(s)

Rule 'cusdep sage sout st_example.sagetex': File changes, etc:

Changed files, or newly in use since previous run(s):

'st_example.sagetex.sage'

Non-existent destination files:

'st_example.sagetex.sout'

------------

Found 0 errors, and 4 warnings in this run

------------

=== Creating rule for 'cusdep sage sout st_example.sagetex'

For rule 'cusdep sage sout st_example.sagetex', running '&do_cusdep( makesout )' ...

Error: You must set the SAGE_ROOT environment variable or run this

script from the SAGE_ROOT or SAGE_ROOT/local/bin/ directory.

Error setting environment variables by sourcing '/usr/local/bin/sage-env';

possibly contact sage-devel (see http://groups.google.com/group/sage-devel).

Rule 'cusdep sage sout st_example.sagetex', function 'makesout'

failed with return code = 256

Collected error summary (may duplicate other messages):

cusdep sage sout st_example.sagetex: Command for 'cusdep sage sout st_example.sagetex' gave return code 256

Command latexmk -pdf -f -r /tmp/latexmkrc -r '/Users/DGola/Library/Application Support/TextMate/Managed/Bundles/LaTeX.tmbundle/Support/config/latexmkrc' st_example.tex exited with status 12

       
 Show hbox, vbox Warnings   Show Latexmk Messages
```

I've had set `SAGE_ROOT` in my `.zshrc` but TextMate seems to ignore that. So I replaced `. $0-env" >&2` in to `/usr/local/bin/sage` (which is a link to `/Applications/SageMath-6.10.app/Contents/Resources/sage/local/bin/sage`) with
```
me="$(test -L "$0" && readlink "$0" || echo "$0")"
SAGE_ROOT=$(dirname $(dirname $(dirname $me)))
. "$me-env" >&2
```

Does not look like a perfect solution to me, but it works.

**Comment by sanssecours** [comment]
I think a better solution would be to just include the path to `sage` in your `PATH` variable inside TextMate:

<img width="829" alt="variables" src="https://cloud.githubusercontent.com/assets/691989/12196790/e5fb1740-b601-11e5-92a5-335a436048ae.png">

The above value for `PATH`: `/Applications/Sage.app/Contents/Resources/sage:/usr/local/bin:$PATH:$HOME/bin:/opt/local/bin` assumes that your version of sage is contained in an Application called `Sage.app` inside the `/Applications` directory. If you want to keep your `PATH` simple, then just use the value `/Applications/Sage.app/Contents/Resources/sage:$PATH`.

**Comment by dagola** [comment]
Yes, you're right. Thats better.

Thanks for your help!

**Comment by sanssecours** [comment]
Glad I could help :).
