### ISSUE TITLE
Clean cleans too much

### ISSUE THREAD

**Issue by tzakharko** [textmate/latex.tmbundle#139]
There is a bug in the implementation of the clean command that can lead to deletion of files that should not be deleted. In particular, when checking for auxiliary files, the code in remove_auxiliary_files() checks for the suffix rather then the extension (the dot is not accounted for). In our particular case, the code was deleting the Fossil checkout information in the file .fslckout

Suggested quick fix: change the line Support/lib/Python/auxiliary.py:167 to

`if isfile(filepath) and any(filepath.endswith(u".%s" % extension) for`

Thanks, 

 Taras

**Comment by sanssecours** [comment]
Hi Taras,

thank you for the bug report. I am currently in the process of overhauling the code for “Clean”. The code on my machine is almost ready and does not show the bug you described. Since I might drop support for systems older than OS X 10.10 in the process, may I ask what version of OS X do you use?

Kind regards,
  René

**Comment by tzakharko** [comment]
Fine with me, we use 10.10+ exclusively! When do you think the new code will be pushed? The majority of our users are non-programmers and they can very confused when the repository suddenly vanishes.

**Comment by sanssecours** [comment]
>  When do you think the new code will be pushed?

I guess today or tomorrow. But I do not make any promises.

> The majority of our users are non-programmers and they get very confused when the repository suddenly vanishes.

The repository will not vanish 😀. My current plan: 

1. Create another branch for OS X 10.9 and below (current state of `HEAD` pushed to GitHub). Maybe I will incorporate the fix you proposed for “Clean” in this branch.
2. Continue with the development on `master`

**Comment by tzakharko** [comment]
No, I meant the vanishing Fossil repository we use for our papers when people use the Clean function. People do Clean, then they try to commit their changes, get an error report and then start doubting their own sanity :) Sorry for the confusion. 

Looking forward to the fix and thank your for the quick reply!
