### ISSUE TITLE
Fix “Convert ASCII Symbol to LaTeX Command”

### ISSUE THREAD

**Issue by sanssecours** [textmate/latex.tmbundle#141]
Currently the command is quite broken. For example if you select `<=>` in the following LaTeX code and press <kbd>^</kbd> + <kbd>⇧</kbd> + <kbd>S</kbd>:
```tex
\documentclass{article}
\begin{document}
$<=>$
\end{document}
```
, then the command replaces the text with
```tex
\documentclass{article}
\begin{docum\Leftrightarrow}
$<=>$
\end{document}
```
instead of
```tex
\documentclass{article}
\begin{document}
$\Leftrightarrow$
\end{document}
```
.

**Comment by tbates** [comment]
thanks for this!
The html bundle has an "Entities" menu item, and a "Convert character to entity" command, bound to cmd-&

It would be great to copy that, so that the same key bindings work and people's html knowledge transfers to latex bundle. I guess to too, that this command works on unicode characters like ≥ as well as ASCII, so character might be a better name.
Many thanks again!

**Comment by sanssecours** [comment]
Hi Tim,

I recently updated the bundle item. It is now called “Convert Symbols in Word / Selection”.

> The html bundle has an "Entities" menu item, and a "Convert character to entity" command, bound to cmd-&

I changed the keyboard shortcut to <kbd>⌘</kbd> + <kbd>&</kbd>.

Section “5.1.5. Symbol Conversion” in the [Help document][] describes the behaviour of the command. Are there any additional characters that the command should convert?

[Help document]: https://github.com/textmate/latex.tmbundle/files/170871/Help.pdf

**Comment by plalteaugal** [comment]
> Section “5.1.5. Symbol Conversion” in the Help document <https://github.com/textmate/latex.tmbundle/files/170871/Help.pdf> describes the behaviour of the command. Are there any additional characters that the command should convert?
> 
> 
5.1.5. Symbol Conversion is not in the current Help document on github.

-Jenny

**Comment by sanssecours** [comment]
Hi Jenny,

> 5.1.5. Symbol Conversion is not in the current Help document on github.

thanks for the hint. Actually I did not include an updated PDF version of the Help document in the repository intentionally. I only regenerate the Help document infrequently, since including updated version of binary data in a git repo takes quite a lot of space. Usually the repository grows about the size of the binary data in such a case. If you want to read the current version of the Help document, please just use the following [link](https://github.com/textmate/latex.tmbundle/files/171128/Help.pdf).

---
[Help.pdf](https://github.com/textmate/latex.tmbundle/files/171128/Help.pdf)
