### ISSUE TITLE
LaTeX bundle preferences not being honored

### ISSUE THREAD

**Issue by abhimat** [textmate/latex.tmbundle#147]
Hi,

I’m trying to change the preferences in my LaTeX bundle, but they are not being honored. Specifically, I’m trying to use pdflatex as my engine and Skim as my viewer, but every time I run Typeset and View, the defaults are used and my PDF shows up in Preview.

Any ideas on what may be wrong?

Thanks!

**Comment by abhimat** [comment]
I have TextMate 1 on my system, and I think I fixed the issue by updating the preferences in the latex prefs window in TextMate 1. Any reason why the LaTeX prefs specified in TextMate 2 might be getting overwritten by the same preferences in TextMate 1?

**Comment by sanssecours** [comment]
Hi Abhimat,

> Specifically, I’m trying to use pdflatex as my engine and Skim as my viewer, but every time I run Typeset and View, the defaults are used and my PDF shows up in Preview.

that is kind of strange. The default viewer is TextMate. Can you please provide the output of the Terminal command `defaults read com.macromates.textmate.preview latexViewer`? In theory the output should be `Skim`.

> I have TextMate 1 on my system, and I think I fixed the issue by updating the preferences in the latex prefs window in TextMate 1. Any reason why the LaTeX prefs specified in TextMate 2 might be getting overwritten by the same preferences in TextMate 1?

The only reason I can think of is, that both versions of TextMate use the same preference file. Currently that should not be the case though. TextMate 1 reads its preferences from the file `com.macromates.textmate`, while TextMate 2 currently uses `com.macromates.textmate.preview`. 

Kind regards,
  René

**Comment by abhimat** [comment]
Thanks for the reply. `defaults read com.macromates.textmate.preview latexViewer` did indeed output `Skim`, and changing the preferences in TextMate 2 does indeed change the output of this command appropriately.

However, the change is not reflected when I run the Typeset & View command in TextMate 2. It still uses whichever settings are in `com.macromates.textmate` rather than `com.macromates.textmate.preview`. I can investigate a little further to see if there’s something specific with my installation…

**Comment by sanssecours** [comment]
> However, the change is not reflected when I run the Typeset & View command in TextMate 2. It still uses whichever settings are in `com.macromates.textmate` rather than `com.macromates.textmate.preview`.

That is very weird behaviour. Did you double check this via `defaults read com.macromates.textmate latexViewer`? The code for reading and writing the preference file in the LaTeX bundle accesses the same file. In theory it should read the same values that it writes. 

Are there any other LaTeX bundles on your machine, besides the one installed inside “Preferences”? If that is the case, can you please remove them? You can check, for LaTeX bundles via the command

```sh
mdfind latex.tmbundle
```

Please remove every bundle except the one in `~/Library/Application Support/TextMate/Managed/Bundles`. If it still does not work you can also try to [revert to defaults](https://github.com/textmate/textmate/wiki/Reverting-To-Defaults).

**Comment by abhimat** [comment]
Through `mdfind`, I found another copy of the LaTeX bundle at `~/Library/Application Support/Avian/Bundles/LaTeX.tmbundle`. Removing this copy of the bundle appears to have solved the problem. Thank you for all your help!
