### ISSUE TITLE
Textmate not identifying .tex files as latex files

### ISSUE THREAD

**Issue by obelkind** [textmate/latex.tmbundle#154]
Hi,

I have a problem with my latex files. Textmate does not identify them as .tex files, and as a result does not identify the environment and typeset commands in the file. When I open the preferences button on the bottom it displays a check mark next to java. I can select the makepdf option, but I can only do this manually. Any suggestions?

**Comment by sorbits** [comment]
In the pop-up at the bottom, set it back to LaTeX and TextMate will 
remember.

The default should be LaTeX, but if you changed it (possibly by 
accident), it’ll remember.

**Comment by obelkind** [comment]
Thanks for the response. When I try to select Latex in the preference menu it reverts back to Java.

**Comment by sorbits** [comment]
Try https://github.com/textmate/textmate/wiki/Reverting-To-Defaults

**Comment by sanssecours** [comment]
> Try https://github.com/textmate/textmate/wiki/Reverting-To-Defaults

If you do not want to remove everything mentioned in the link from Allan: Just removing `~/Library/Application Support/TextMate/Global.tmProperties` and restarting TextMate after that, should most likely fix your issue.

**Comment by sanssecours** [comment]
Closing this due to a lack of response;

@obelkind If the issue still persists, then please just comment below. Thanks.
