### ISSUE TITLE
Where is the `.tmLanguage` file for LaTeX?

### ISSUE THREAD

**Issue by colasbd** [textmate/latex.tmbundle#157]
I would like to use the library [SyntaxKit](https://github.com/alehed/SyntaxKit) with LaTeX but I can't find the `.tmLanguage` file, which is required.

Where is it?

Thanks

**Comment by sanssecours** [comment]
Hi Colas,

you can find the grammar file for LaTeX [here](https://github.com/textmate/latex.tmbundle/blob/master/Syntaxes/LaTeX.plist).

Kind regards,
  René

**Comment by colasbd** [comment]
Thanks @sanssecours.
I've tried with this file but I still have the issue described [there](https://github.com/soffes/SyntaxKit/issues/19). 
If you can help, it would be great. Thanks!
