### ISSUE TITLE
The 'clean' tool may break git repos

### ISSUE THREAD

**Issue by rbost** [textmate/latex.tmbundle#161]
The 'clean' tool of the LaTeX bundle removes all the files ending with the .idx extension, including the ones that might be present in a .git/objects/pack directory (cf. https://git-scm.com/book/en/v2/Git-Internals-Packfiles).
This is a huge problem because running 'clean' in a git repo with such a file simply breaks the repo (without any way to easily recover).

One should be able to explicitly give a list of directories which must not be visited by 'clean', with a default to .git, .hg, .svn, ...
For the moment, a workaround is to remove the .idx matching regex in `config/auxiliary.yaml`.

Modifying `config/auxiliary.yaml` is not enough to properly fix this issue: this file defines regex on filenames, and do not take directories into account.

**Comment by sanssecours** [comment]
Hi Raphael,

thank you for reporting this issue. Sorry for introducing this problem in the first place 😳. I hope you could restore your Git repository. I (hopefully) fixed the problem in commit 9d330182. The command should now ignore files in hidden subdirectories. 

Kind regards,
  René
