### ISSUE TITLE
triggers such as "thm" duplicate user's environment name

### ISSUE THREAD

**Issue by scoskey** [textmate/latex.tmbundle#173]
This is not a bug at all, but a usage consideration.

The package allows one to write "thm" followed by ctrl+< to obtain a \begin{theorem}\end{theorem} environment. The environment automatically includes a \label{...}. The cursor is inserted in the label, the label is not selected for potential deletion.

1. Do users want to provide a label for every theorem?

2. I have long used the theorem name "thm", as in \newtheorem{thm}{Theorem}. This means I want this same command to create \begin{thm}\end{thm}. I suppose one might consider my particular choice to be deprecated by the advent of your editor macros, but I'm not sure.

https://github.com/textmate/latex.tmbundle/blob/b06ddd1f4e969c3ae4188b68a0b8302bb91aeb28/Support/config/latex.config#L129

**Comment by sanssecours** [comment]
Hi Samuel,

you can configure “Insert”→“Command Based on Current Word“ to your liking via the command “Edit Configuration File“. For more information please take a look at the section “Inserting Commands and Environments“ in the [Help document](https://github.com/textmate/latex.tmbundle/blob/master/Support/help/Help.pdf) (also available in TextMate via “Bundles”→“LaTeX”→“Help”).

**Comment by scoskey** [comment]
Ok, understood!
