### ISSUE TITLE
[question] is "Latex Watch" mostly a latexmk wrapper or is there more?

### ISSUE THREAD

**Issue by ataiya** [textmate/latex.tmbundle#177]
Is the latex watch mostly a UI wrapper over latexmk, or do you guys do something else on top of it? (like caching the parsing of the imported packages?)

!TL;DR 
As I need to work across OS's extensively, I am transitioning to VisualStudioCode for most of my coding (C++,Python,Latex). Regarding Latex compile, it still seem to me that TextMate compiles documents a lot faster than VSCode, and I would like to understand why that is the case!

**Comment by sanssecours** [comment]
> Is the latex watch mostly a UI wrapper over latexmk, or do you guys do something else on top of it? 

Basically LaTeX Watch

1. compiles a TeX file using Latexmk,
2. displays the resulting PDF file, and
3. checks the log file for errors/warnings.

The script repeats these steps every time a file was changed. You can check out the main loop of the script [here](https://github.com/textmate/latex.tmbundle/blob/master/Support/bin/latex_watch.pl).

> (like caching the parsing of the imported packages?)

The script does not do any additional caching.

**Comment by ataiya** [comment]
Thanks! So there should be no performance difference
