### ISSUE TITLE
Watch Document closes Skim

### ISSUE THREAD

**Issue by rodrigoalcarazdelaosa** [textmate/latex.tmbundle#181]
Hi there,

I'm using the latest version of Textmate 2.0 together with Skim 1.5.5 (121). When trying to **watch** my document, Skim opens but then automatically closes (I'm also using Latexmk). This didn't happened before MacOS Catalina (I'm under 10.5.1). If I just typeset & view everything is fine. My current workaround right now is to have both apps opened (Textmate and Skim) and just hit cmd-R every time I want to update Skim.

Anyone facing the same issue?
Thanks in advance!
Rodrigo

**Comment by sanssecours** [comment]
Hi Rodrigo,

> Anyone facing the same issue?

thank you for reporting the bug. This is a known issue. The command “Watch Document” uses [CocoaDialog, which does not work on macOS 10.15](https://github.com/textmate/bundle-support.tmbundle/issues/31). This is the case, since the version of CocoaDialog included with TextMate is still a 32-bit executable.

**Comment by jonathan-gray-iss** [comment]
I am, as well.

**Comment by mcnees** [comment]
Just seconding the need for a fix. This incompatibility is the one thing keeping me from upgrading to 10.15.

**Comment by plalteaugal** [comment]
I second this.

**Comment by dalmiral** [comment]
Would be grateful for a fix or any news about this. Thank you all, kindly.

**Comment by sanssecours** [comment]
I opened a pull request that should fix this problem [here](https://github.com/textmate/bundle-support.tmbundle/pull/32). For a quick fix you can also follow the steps below.

1. Download the updated Bundle Support bundle: [Bundle Support.tmbundle.zip](https://github.com/textmate/latex.tmbundle/files/4339537/Bundle.Support.tmbundle.zip)
2. Unarchive the zip file
3. Replace 

   ```
   ~/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle` 
   ``` 
   
   with the bundle from step 2 (here `~` refers to your home folder e.g. `/Users/rene`)

**Comment by rodrigoalcarazdelaosa** [comment]
> I opened a pull request that should fix this problem [here](https://github.com/textmate/bundle-support.tmbundle/pull/32). For a quick fix you can also follow the steps below.
> 
> 1. Download the updated Bundle Support bundle: [Bundle Support.tmbundle.zip](https://github.com/textmate/latex.tmbundle/files/4339537/Bundle.Support.tmbundle.zip)
> 2. Unarchive the zip file
> 3. Replace
>    ```
>    ~/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle` 
>    ```
>    
>    
>    with the bundle from step 2 (here `~` refers to your home folder e.g. `/Users/rene`)

This worked like a charm, thanks a lot!

**Comment by dalmiral** [comment]
This worked - Thank you so much!

**Comment by plalteaugal** [comment]
I did what you said and got this: “Skim does not appear to be installed on your system.” Now my pdf output to skim won’t open. What to do?

Jenny

**Comment by sanssecours** [comment]
> I did what you said and got this: “Skim does not appear to be installed on your system.” Now my pdf output to skim won’t open. What to do?

Can you please describe [steps to reproduce the error](https://github.com/textmate/textmate/wiki/Writing-Bug-Reports) Jenny? I tried the steps below, which worked as expected on my system.

1. Open TextMate
2. Create a new document (<kbd>⌘</kbd> + <kbd>N</kbd>)
3. Store the following text in the document

   ```tex
   \documentclass{article}
   
   \begin{document}
     Test
   \end{document}
   ```

4. Save the document as `Test.tex` in the `Downloads` folder (<kbd>⌘</kbd> + <kbd>S</kbd>)
5. Invoke “Watch Document” (<kbd>^</kbd> + <kbd>⌘</kbd> + <kbd>W</kbd>)
6. TextMate translates the document and shows the resulting PDF in Skim
7. Put the caret behind the word `Test`
8. Invoke ”Jump to Current Line in Viewer” (<kbd>^</kbd> + <kbd>⌥</kbd> + <kbd>⌘</kbd> + <kbd>O</kbd>)
9. Skim jumps to the bottom of the PDF document

**Comment by plalteaugal** [comment]
After step 5, I got this:



If I skip step 5, I get this:

**Comment by sanssecours** [comment]
Thank you for the fast reply Jenny.

> After step 5, I got this:

GitHub seems to remove attachments, if you add a comment via email. I assume you wanted to add the picture below to your comment?

<img width="540" alt="LaTeX Watch Error" src="https://user-images.githubusercontent.com/691989/76935716-e1a02f80-68f1-11ea-9115-ec29126f91ec.png">

> If I skip step 5, I get this:

Would the image you probably attached here look like the one below?

![Show Current Line - Error Message](https://user-images.githubusercontent.com/691989/76936620-840ce280-68f3-11ea-81cb-4dd7735e3514.png)

It seems [`find_app`](https://github.com/textmate/bundle-support.tmbundle/blob/master/Support/shared/bin/find_app) is unable to locate your version of Skim. Can you please follow the steps below and report the outcome on your computer?

1. Open Terminal (`/Applications/Utilities/Terminal.app`)
2. Enter the following command

   ```
   ~/Library/Application\ Support/TextMate/Managed/Bundles/Bundle\ Support.tmbundle/Support/shared/bin/find_app Skim.app
   ```

Can you please also tell me where you installed Skim on your computer? Does opening the LaTeX Bundle preferences (Menu “Bundles” → “LaTeX” → “Preferences…” inside TextMate) work on your machine?

**Comment by plalteaugal** [comment]
Dear René,

Thank you for your help. My students are waiting for a pdf, so we are all grateful for whatever you can do.  

>> On Mar 18, 2020, at 12:52 AM, René Schwaiger <notifications@github.com> wrote:
> ﻿
> Thank you for the fast reply Jenny.
> 
> After step 5, I got this:
> 
> GitHub seems to remove attachments, if you add a comment via email. I assume you wanted to add the picture below to your comment?
> 
> 
> 
The error message was: “Cocoadialog” cannot be opened because the developer cannot be verified.
> If I skip step 5, I get this:
> 
> Would the image you probably attached here look like the one below?
> 
> 
> 
The error message was: “find_app” cannot be opened because the developer cannot be verified.
> It seems find_app is unable to locate your version of Skim. Can you please follow the steps below and report the outcome on your computer?
> 
> Open Terminal (/Applications/Utilities/Terminal.app)
> 
> Enter the following command
> 
> ~/Library/Application\ Support/TextMate/Managed/Bundles/Bundle\ Support.tmbundle/Support/shared/bin/find_app Skim.app
When I did this, I got the same message “find_app” cannot be opened because the developer cannot be verified.
> 
> Can you please also tell me where you installed Skim on your computer?
> 
Skim is in my Applications Folder
> Does opening the LaTeX Bundle preferences (Menu “Bundles” → “LaTeX” → “Preferences…” inside TextMate) work on your machine?
> 
Yes

**Comment by mcnees** [comment]
Will TextMate update this bundle automatically?

**Comment by sanssecours** [comment]
Looks like these problems occur, because I did not sign the bundle I uploaded. Since Allan already [merged my pull request into the Bundle Support bundle](https://github.com/textmate/bundle-support.tmbundle/commit/13169c6209ebb02564009c4ce573d62452c9b3ae) these errors should go away once the bundle is updated on your machine. Can you please check if the bundle was updated, by following the steps below?

1. Open TextMate
2. Open the menu item “TextMate” → “About TextMate”
3. Select the tab “Bundles“
4. There should be an entry “**Bundle Support:** Add 64-bit version of CocoaDialog“

   <img width="661" alt="Bundles" src="https://user-images.githubusercontent.com/691989/77003288-5f4d5500-695d-11ea-8241-4983124ebd17.png">

If that entry is there, can you please check if translating LaTeX documents works now?

**Comment by sanssecours** [comment]
> Will TextMate update this bundle automatically?

Yes.

**Comment by plalteaugal** [comment]
> On Mar 18, 2020, at 1:25 PM, René Schwaiger <notifications@github.com> wrote:
> 
> 
> Looks like these problems occur, because I did not sign the bundle I uploaded. Since Allan already merged my pull request into the Bundle Support bundle <https://github.com/textmate/bundle-support.tmbundle/commit/13169c6209ebb02564009c4ce573d62452c9b3ae> these errors should go away once the bundle is updated on your machine. Can you please check if the bundle was updated, by following the steps below?
> 
> Open TextMate
> 
> Open the menu item “TextMate” → “About TextMate”
> 
> Select the tab “Bundles“
> 
> There should be an entry “Bundle Support: Add 64-bit version of CocoaDialog“
> 
>  <https://user-images.githubusercontent.com/691989/77003288-5f4d5500-695d-11ea-8241-4983124ebd17.png>
> If that entry is there, can you please check if translating LaTeX documents works now? 
> 
The March 2020 entry is not there. January 2020 is the last entry I see. I went to “Check for update” but was told I have version 2.0.6 which is supposedly the latest version. 

I will try to get the latest version directly from GitHub.

**Comment by plalteaugal** [comment]
> On Mar 18, 2020, at 8:56 PM, Jenny Harrison <profharrison@gmail.com> wrote:
> 
> 
> 
>> On Mar 18, 2020, at 1:25 PM, René Schwaiger <notifications@github.com <mailto:notifications@github.com>> wrote:
>> 
>> 
>> Looks like these problems occur, because I did not sign the bundle I uploaded. Since Allan already merged my pull request into the Bundle Support bundle <https://github.com/textmate/bundle-support.tmbundle/commit/13169c6209ebb02564009c4ce573d62452c9b3ae> these errors should go away once the bundle is updated on your machine. Can you please check if the bundle was updated, by following the steps below?
>> 
>> Open TextMate
>> 
>> Open the menu item “TextMate” → “About TextMate”
>> 
>> Select the tab “Bundles“
>> 
>> There should be an entry “Bundle Support: Add 64-bit version of CocoaDialog“
>> 
>>  <https://user-images.githubusercontent.com/691989/77003288-5f4d5500-695d-11ea-8241-4983124ebd17.png>
>> If that entry is there, can you please check if translating LaTeX documents works now? 
>> 
> The March 2020 entry is not there. January 2020 is the last entry I see. I went to “Check for update” but was told I have version 2.0.6 which is supposedly the latest version. 
> 
> I will try to get the latest version directly from GitHub. 

I am afraid I need a simple link to click on. I ended up downloading bundle-support.tmbundle-master and do not know what to do with it. (Sorry for my ignorance!)

Jenny

**Comment by sanssecours** [comment]
> The March 2020 entry is not there. January 2020 is the last entry I see. I went to “Check for update” but was told I have version 2.0.6 which is supposedly the latest version.

That is the correct latest stable version of TextMate. I also use that version of the application.

TextMate uses additional software components, called bundles, to offer extended functionality such as syntax highlighting. These bundles are updated independently from the main application. You can check, when a bundle was updated in “TextMate” → “Preferences…” → “Bundles”.

<img width="896" alt="Bundles" src="https://user-images.githubusercontent.com/691989/77034997-b67a1680-69ab-11ea-8885-63ba3719bf16.png">

Can you please check if the switch “Check for and install updates automatically” is enabled on your machine? If it is, then TextMate should overwrite the Bundle support bundle in `~/Library/Application Support/TextMate/Managed/Bundles` with the updated version of the bundle sometimes in the next hours. If you have the same date entry “16.03.2020” besides the entry for the “Bundle Support” bundle, then you should already have the correct version. 

If the [steps described above](https://github.com/textmate/latex.tmbundle/issues/181#issuecomment-599889830) still do not show the expected result on your machine, then please follow the steps below.

1. Quit TextMate
2. Remove the folder `~/Library/Application Support/TextMate/Managed/Bundles`. For now please only move the folder to the Trash and **do not empty** the Trash. This way you can replace the folder with an old version again, if anything goes wrong.
3. Restart TextMate
4. TextMate should recreate the folder removed in step `2.`
5. Open “TextMate” → “Preferences…” → “Bundles”
6. The date for the “Bundle Support“ bundle should show the date `27.12.2019` (or the same date in a different date format)

   <img width="896" alt="Bundles Pristine" src="https://user-images.githubusercontent.com/691989/77036475-8cc2ee80-69af-11ea-8bdb-1227f67a211f.png">

7. Install the LaTeX bundle by clicking the checkbox right next to it

After step `7.` translating a document with “Typeset & View (PDF)” (<kbd>⌘</kbd> + <kbd>R</kbd>) should work again. The command “Watch Document” should work again, after the “Bundle Support” bundle was auto-updated.

**Comment by sorbits** [comment]
> Looks like these problems occur, because I did not sign the bundle I uploaded. Since Allan already [merged my pull request into the Bundle Support bundle](https://github.com/textmate/bundle-support.tmbundle/commit/13169c6209ebb02564009c4ce573d62452c9b3ae) these errors should go away once the bundle is updated on your machine

I’m actually a little unsure about this issue.

@plalteaugal reports the error is that the “developer cannot be verified” for both `find_app` and `CocoaDialog`.

Neither of these two executables have been signed (with Apple’s `codesign`), but I am not getting a problem on macOS 10.15 with default (GateKeeper) settings.

I *think* the default policy is to open unsigned applications (without warnings) when executed via the shell (i.e. basically only double-click in Finder causes a warning). But we may have to start signing all executables shipped with bundles, to avoid any problems.

For now, as a test, if @plalteaugal could try signing the executables themselves by running these two commands in a terminal:

    codesign -s - ~/Library/Application\ Support/TextMate/Managed/Bundles/Bundle\ Support.tmbundle/Support/shared/bin/find_app
    codesign -s - --deep ~/Library/Application\ Support/TextMate/Managed/Bundles/Bundle\ Support.tmbundle/Support/shared/bin/CocoaDialog.app

That should given them an “ad hoc” signature, although I am not sure how succesful the CocoaDialog signing is because of the embedded frameworks — I got a warning about ambiguous subcomponents, but I get no warning when opening the application via Finder, but then, if I re-install CocoaDialog (ensuring it gets a new inode, as signing seems to be cached by inode), I still get no warning from opening CocoaDialog via Finder.

**Comment by plalteaugal** [comment]
> On Mar 18, 2020, at 11:43 PM, Allan Odgaard <notifications@github.com> wrote:
> 
> 
> Looks like these problems occur, because I did not sign the bundle I uploaded. Since Allan already merged my pull request into the Bundle Support bundle <https://github.com/textmate/bundle-support.tmbundle/commit/13169c6209ebb02564009c4ce573d62452c9b3ae> these errors should go away once the bundle is updated on your machine
> 
> I’m actually a little unsure about this issue.
> 
> @plalteaugal <https://github.com/plalteaugal> reports the error is that the “developer cannot be verified” for both find_app and CocoaDialog.
> 
> Neither of these two executables have been signed (with Apple’s codesign), but I am not getting a problem on macOS 10.15 with default (GateKeeper) settings.
> 
> I think the default policy is to open unsigned applications (without warnings) when executed via the shell (i.e. basically only double-click in Finder causes a warning). But we may have to start signing all executables shipped with bundles, to avoid any problems.
> 
> For now, as a test, if @plalteaugal <https://github.com/plalteaugal> could try signing the executables themselves by running these two commands in a terminal:
> 
> codesign -s - ~/Library/Application\ Support/TextMate/Managed/Bundles/Bundle\ Support.tmbundle/Support/shared/bin/find_app
> codesign -s - --deep ~/Library/Application\ Support/TextMate/Managed/Bundles/Bundle\ Support.tmbundle/Support/shared/bin/CocoaDialog.app
> That should given them an “ad hoc” signature, although I am not sure how succesful the CocoaDialog signing is because of the embedded frameworks — I got a warning about ambiguous subcomponents, but I get no warning when opening the application via Finder, but then, if I re-install CocoaDialog (ensuring it gets a new inode, as signing seems to be cached by inode), I still get no warning from opening CocoaDialog via Finder.
> 
> —
> 

Hi Alan,

I tried this, but to no avail! 

I will try what Rene proposed as soon as I have a few more minutes free.

I appreciate your help as always. Rene is also wonderful!

Jenny

p.s. This problem is trivial compared to what happened years ago when I followed some instructions from this group to obtain a split screen. Little did I know that it was a joke and I ended up erasing my disk drive! You probably remember this. Now I can laugh.

**Comment by plalteaugal** [comment]
I had to erase from my hard drive every copy of Bundle Support to get your instructions to work. There were half a dozen by this point. Now all is well.  Many thanks!

Jenny

**Comment by mcnees** [comment]
Is anyone getting this to work on Big Sur? It compiles, opens Skim, but then fails with "The command 'check_open -s Skim test.pdf' failed to execute: Bad CPU type in executable."
