### ISSUE TITLE
cite autocomplete: no selection window

### ISSUE THREAD

**Issue by daviehh** [textmate/latex.tmbundle#182]
Hi, thanks for this excellent tool to support latex in textmate! I'm just trying this out, using option-esc(or command-esc), the \cite{...} cycles through the entries in my bib file but I cannot get a selection window to show up.  Are there any additional setting that needs to be applied? Textmate version 2019-09-15 (v2.0), and tested with both the released and the github current version of latex.tmbundle.

**Comment by sanssecours** [comment]
👋 Hi,

one reason for not showing a menu when you press <kbd>⌥</kbd> + <kbd>Esc</kbd> might be that the cite key at the current caret position is already unique. Maybe that is also the case for your example. Can you please try, if the steps below work on your machine?

1. Store the text:

   ```bib
   @webpage{two,
    Author = {Two},
    Date-Added = {2019-12-11 11:06:01 +0100},
    Date-Modified = {2019-12-11 11:06:23 +0100},
    Month = {2},
    Title = {Two},
    Url = {two.org},
    Year = {2},
    Bdsk-Url-1 = {two.org}}
   
   @webpage{one,
    Author = {One},
    Date-Added = {2019-12-11 11:02:23 +0100},
    Date-Modified = {2019-12-11 11:04:49 +0100},
    Month = {1},
    Title = {One},
    Url = {one.org},
    Year = {1},
    Bdsk-Url-1 = {one.org}}
   ```

   in the file `References.bib` in your `Downloads` folder.

2. Create a file called `Completions.tex` with the content:

   ```tex
   \documentclass{article}
   
   \usepackage{biblatex}
   
   \addbibresource{References.bib}
   
   \begin{document}
   \cite{}
   \end{document}
   ```

   and store it into the `Downloads` folder.

3. Open the file from the last step again and insert the caret between the braces of the `cite` command.

4. Press <kbd>⌥</kbd> + <kbd>Esc</kbd>

5. TextMate should now display the menu below.

   <img width="272" alt="Completion" src="https://user-images.githubusercontent.com/691989/70613584-2f2d4200-1c09-11ea-8492-baf6231a5afc.png">

**Comment by daviehh** [comment]
Thanks for the details! Turns out in my case the problem is not the bib file but keyboard customizer (Karabiner) somehow messing with the shortcut even though ⌥ + Esc is not mapped...sorry for the trouble and thanks again!
