### ISSUE TITLE
Add starred versions of section commands to bundle

### ISSUE THREAD

**Issue by wienen** [textmate/latex.tmbundle#186]
Hi,

Can we add starred versions of section commands to the bundle? Like `\section*{}` et cetera? I can add those if necessary, not sure if this package is still maintained.

Cheers,

Hans

**Comment by sanssecours** [comment]
Hi Hans,

as far as I can tell the bundle already supports starred environments. To change the current environment to its starred version you can use the command “Toggle Starred” (<kbd>^</kbd> + <kbd>*</kbd>). For example, to create the starred version of a section you can use the following steps:

1. Open a `.tex` file in TextMate
2. Enter the text `sec`
3. Press the tab key (<kbd>⇥</kbd>) to create a section environment
4. Enter the text of your section environment (e.g. “Something”)
5. Use the command “Toggle Starred” to create a starred version of the current environment (i.e. replace `\section` with `\section*`)

If I use the steps above in an empty `.tex` file, then the content of the file should look like this afterwards:

```tex
\section*{Something} % (fold)
\label{sec:something}

% section something (end)
```

You can use “Toggle Starred” (<kbd>^</kbd> + <kbd>*</kbd>) again, if you you would like to use a non-starred section environment instead. Hope the description above helps.

Kind regards,
  René

**Comment by wienen** [comment]
Hi René,

You are completely right. I somehow missed that key combination. Thanks!

I'll close the issue.
