### ISSUE TITLE
Problem with parsing UTF-8 on macOS with Python3

### ISSUE THREAD

**Issue by borismotik** [textmate/latex.tmbundle#192]
Since macOS Monterey dropped Python2 and the LaTeX scripts were updated to use Python3, I've been running into an issue related to parsing UTF-8 in the output of pdflatex. I don't know why LaTeX produces malformed UTF-8 output. However, I see that the scripts for the Python2 were written to anticipate this, but this doesn't work with Python3. The problem seems to be in the `parsing.py` file, where `self.input_stream.readline()` will throw `UnicodeDecodeError` exception in Python3 if it finds malformed UTF-8 input. Thus, the code starting from line 128 should probably written as follows, so that exception handling applies to both Python2 and Python3.

```
        def to_utf8(string):
            if PYTHON2:
                for encoding in encodings:
                    return string.decode(encoding)
            else:
                return string

        statement = ""
        while True:
            try:
                line = to_utf8(self.input_stream.readline())
                if not line:
                    return statement
                statement += line.rstrip('\n')
                if not (len(line) == 80 and not line[78] in {'!', '.', ')'}):
                    break
            except UnicodeDecodeError:
                continue
        return statement + '\n'
```

In fact, my problem goes away if I change the code myself as stated above; however, every subsequent update of the LaTeX bundle in TextMate overwrites this change, so it would be good to integrate this change into the bundle itself.

**Comment by sanssecours** [comment]
Hi Boris,

thank you for the bug report. Can you please [add steps (including a minimal TeX document) to reprodcue the problem](https://github.com/textmate/bugs#writing-bug-reports). If the code above does indeed fix the problem, then a [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) would be very helpful too 😊.

**Comment by borismotik** [comment]
Hello,

**Comment by borismotik** [comment]
Hello,

It’s hard for me to provide a reproducer as this depends on the output of LaTeX. I’ll provide you with a pull request. Thank you!

Boris

**Comment by borismotik** [comment]
Hello,

I’ve just tried to create a pull request by checking in my changes on a branch, but I haven’t got permissions to push on a new branch. Also, forking a repo seems like too much of an overhead, given that it’s quite a simple change.

Hence, I’ve attached the modified Python file to this comment: all you need to do is copy it to `latex.tmbundle/Support/lib/Python`. The correctness of the proposed change should be self-evident: the catching of UnicodeDecodeError needs to be moved higher up the call stack so that it is uniformly caught on both Python 2 and Pyton 3. On Python 3, the exception will be thrown in `self.input_stream.readline()`, which breaks the current version of the code.

Now I don't know why my LaTeX installation benerates malformed UTF-8 in the log. I saw that this happens only sometimes, so I presume that this depends on the collection of used packages. In any case, I’ve used the modified file for some time now and it all is working swimmingly again.

Regards,

Boris

[parsing.py.zip](https://github.com/textmate/latex.tmbundle/files/8472525/parsing.py.zip)

**Comment by hoyois** [comment]
I had the same issue with some of my LaTeX files and @borismotik's solution works for me, thank you!
