### ISSUE TITLE
First TeX command is not recognized if last line contains comment

### ISSUE THREAD

**Issue by muzimuzhi** [textmate/latex.tmbundle#200]
Recently I find on GitHub.com, in rendered markdown, in a fenced code block highlighted with `tex` language (` ```tex `), if the previous line contains TeX comment (`%` followed by none or more characters), then the first command on current line is not recognized as TeX command any more.

But if current line contains leading space(s), then the highlighting for first command is repaired.

```tex
\relax \relax
%
\relax \relax
%
 \relax \relax
```

![image](https://github.com/textmate/latex.tmbundle/assets/6376638/6cf2db2b-48ec-4359-a9a7-5cd24e6abad5)

The only change made to the most recent release of https://github.com/github-linguist/linguist (see https://github.com/github-linguist/linguist/pull/6627) was my three commits that altered list of TeX primitives (https://github.com/textmate/latex.tmbundle/compare/8e472548d189604712739a925dbdd735069e0668...0be3da8fd8de49a8bfc178a71728e6bfb5117570). They are most likely the culprit, but I can't find the reason.

Maybe that's controlled by other repositories, for instance https://github.com/github/markup. But the most recent commit in that repo was two months ago...

**Comment by sanssecours** [comment]
Thank you for the bug report. I do not think the problem you describe has anything to do with the updates to the TeX grammar in this Bundle. At least in TextMate everything seems to work as expected. I tried the following:

1. Open TextMate
2. Create a new file (<kbd>⌘</kbd> + <kbd>N</kbd>)
3. Change the syntax to TeX: Choose “TeX” in the second column of the status bar
5. Past the following text:
    
   ```
   \relax \relax
   %
   \relax \relax
   %
   \relax \relax
   ```

You can see the output on my machine in the following screenshot:

<img width="506" alt="TeX Highlighting" src="https://github.com/textmate/latex.tmbundle/assets/691989/1efd390d-5ea9-4277-a8e8-ee5003f7db03">

**Comment by muzimuzhi** [comment]
Thank you for sharing the (positive) info!

Then I think I will report this to a more general place which is closer to GitHub team.

**Comment by muzimuzhi** [comment]
I didn't report it elsewhere but it seems the issue is now fixed.

![image](https://github.com/textmate/latex.tmbundle/assets/6376638/016a12a4-b52d-4de7-963c-3b7294585193)
