### ISSUE TITLE
Open Included Item has issues in nested documents

### ISSUE THREAD

**Issue by penx** [textmate/latex.tmbundle#25]
I have a master file in a root directory, say /master.tex and and include a chapter say, /chapters/ch1.tex.

In ch1.tex I input another file, '\input{./quotes/quote1}'. Note - Latex requires that this link is relative to the master file, not ch1.tex.

If I hit enter on this line to trigger the 'Open Included Item' macro, then I am not taken to the /quotes/quote1.tex file as TextMate is seeing this link as being relative to ch1.tex

**Comment by sanssecours** [comment]
Hi penx,

instead of specifying `TM_LATEX_MASTER`, you can also add the following to the first lines of the file `ch1.tex`: 
```latex
%!TEX root = ../master.tex
```
Hope this fixes your issue. If it does not, then please comment below or open a new issue.

Thanks,
  René
