### ISSUE TITLE
Close Log Window Option Ignored in TM2

### ISSUE THREAD

**Issue by felixjung** [textmate/latex.tmbundle#26]
The option to "keep log window open" in the LaTeX bundle preferences is being ignored in TM2 -- with the option disabled the log pane isn't closed after Typeset & View is done.

TM2 (9276)

**Comment by sanssecours** [comment]
Hi S.V.,

> I realized that in v2.0-beta.6.4 the log window is not closing anymore.

thank you for the bug report! The issues should be fixed in commit e85301a3.

Kind regards,
  René
