### ISSUE TITLE
show outline fails on nested inputs in folders (with fix)

### ISSUE THREAD

**Issue by anton3s** [textmate/latex.tmbundle#5]
I found a bug in the Show Outline command.
It occurs when I use nested inputs in combination with files in different folders.

% main.tex
\input{somefolder/a}

% a.tex
\input{somefolder/b}

LaTeX interprets this as a.tex and b.tex both being in the same folder /somefolder, while in the Show Outline command it is interpreted as b.tex being in /somefolder/somefolder.

I fixed this in my version by passing the rootfilename into the outline_points function:
line 33
def outline_points(filename) ===> def outline_points(filename,rootfilename)
line 46
points += outline_points(filename.adjust_end($1)) if ... ===> points += outline_points(rootfilename.adjust_end($1),rootfilename) if ... 
line 57
points = outline_points(file) ===> points = outline_points(file,file)

I have no idea how to update the git version (and I don't have the time to look into this now), so if anyone is interested in adding this fix on my behalf, feel free to do so. ;-)

Anton

**Comment by sanssecours** [comment]
Hi Anton,

it seems this bug has been fixed. I used the following steps to try to reproduce the problem:

1. Create a file called `main.tex` with the following content:  
    ```latex
    \documentclass{article}
    \begin{document}
    \input{somefolder/a}
    \end{document}
    ```
    
2. Create a subfolder `somefolder`
3. Create a file called `a.tex` inside the folder `somefolder` with the following content:   

    ```latex
    \input{somefolder/b}
    ```

4. Create a file called `b.tex` inside the folder `somefolder` with the following content:  
    ```latex
    \section{Section}
    ``` 
    
5. Open `main.tex` in TextMate
6. Call “Show Outline” by pressing <kbd>⌥⌘O</kbd>  
7. The HTML output shows the only section `Section`. The link in the HTML output correctly points to the file `somefolder/b.tex`

If the above steps do not correctly reproduce the bug you encountered, then please comment below.

Thanks,
  René
