### ISSUE TITLE
Latex bundle command "Label based on current word/selection" is broken if using multiple .tex files

### ISSUE THREAD

**Issue by coccoinomane** [textmate/latex.tmbundle#52]
Dear all,

I am running TextMate version 2.0-alpha.9399.  I am writing my thesis using multiple .tex files. I have a master file which includes several chapters, each corresponding to a separate tex file.

When I am in one of the chapter files, the command "Label based on current word/selection" (shortcut alt + esc) does not work and gives me the error message attached below. Interestingly enough, the command works fine when called from the master file, even when referring to a label defined in the children files.

Here is how to reproduce the problem. Create a test.tex file like this one:

\documentclass{article}
\begin{document}
  
\section{Section 1}
\label{section1}
Ciao

\section{Section 2}
\label{section2}
Sec. \ref{section1} is well written.

\input{include}
Just included Section 3.

\end{document}

and an include.tex file like this one in the same directory:

%!TEX root = test.tex
\section{Section 3}
\label{section3}
This is Section 3. sec

Then invoke the command (alt + esc) next to 'sec' in the include.tex file. At this point, I obtain the error pop-up below. 

Please note that this does not happen in Textmate1. It is a little bit of a pain because when the file gets sizeable I spend most of my time hunting down for references.

Thank you for your attention,
Guido Pettinari

Failure running “Label Based on Current Word / Selection…”.
/Users/coccoinomane/Library/Application Support/TextMate/Managed/Bundles/LaTeX.tmbundle/Support/lib/LaTeXUtils.rb:19:in `initialize': No such file or directory - /Users/coccoinomane/Downloads/test.tex (Errno::ENOENT)
	from /Users/coccoinomane/Library/Application Support/TextMate/Managed/Bundles/LaTeX.tmbundle/Support/lib/LaTeXUtils.rb:19:in `open'
	from /Users/coccoinomane/Library/Application Support/TextMate/Managed/Bundles/LaTeX.tmbundle/Support/lib/LaTeXUtils.rb:19:in `options'
	from /Users/coccoinomane/Library/Application Support/TextMate/Managed/Bundles/LaTeX.tmbundle/Support/lib/LaTeXUtils.rb:45:in `master'
	from /Users/coccoinomane/Library/Application Support/TextMate/Managed/Bundles/LaTeX.tmbundle/Support/lib/LaTeXUtils.rb:56:in `get_labels'
	from Label Based on Current Word / Selection…:8

**Comment by sanssecours** [comment]
Hi,

I just wanted to look into this issue. The example by Guido works correctly for me. Did Michael fix the issue in commit 83792653? Can anybody still reproduce the problem?

Kind regards,
  René

**Comment by sanssecours** [comment]
Hi again,

I just updated the bundle code responsible for “Label Based on Current Word/Selection”. Hopefully the current code works for you Guido. It does for me if I save `test.tex` and `include.tex` in the same folder. If you still have problems, then please comment below or open a new issue.

Kind regards,
  René

**Comment by coccoinomane** [comment]
It works perfectly, thank you very much sansecours! Now my life will be much easier :-)
