### ISSUE TITLE
cite autocomplete

### ISSUE THREAD

**Issue by sambura** [textmate/latex.tmbundle#53]
Hi,
I recently discovered TextMate 2 and decided to write my bachelortheses with it. 
when i insert a citation (insert-> citation, ctrl-{ ) it automatically inserts the first entry of my bibtex file. I think it should instead show a menu to pick the right entry.
Also, I would expect TextMate to show me a list of my bibtex entries when autocompleting (by pressing esc). Is this not yet implemented?
I would thank anyone who can clarify.
Greatings, Daniel

**Comment by sanssecours** [comment]
Hi,

the last update should fix some problems concerning “Insert Citation”. If you have any problems with the new code, then please comment below or open a new issue. Please do not forget to also include steps to reproduce the problem.

Thanks,
  René

By the way: One of the easiest way to insert a citation: 

1. Open a tex file
2. Navigate to the place where you want to place the reference
3. Press <kbd>⌥⎋</kbd>
4. Press <kbd>2</kbd>
5. Select the citation you want

You can also narrow down the list of citations by writing down some characters that are part of the citation before you press <kbd>⌥⎋</kbd>. This even works with regex patterns. For example: If you want all citations that contain `Xen` or `xen` then select the pattern `[Xx]en` before step 3.
