### ISSUE TITLE
Syntax Issue With Double Dollar Sign ($$)

### ISSUE THREAD

**Issue by coccoinomane** [textmate/latex.tmbundle#75]
Dear all,

When using the Latex bundle, I find that all the text following a double dollar sign $$ is highlighted as if it was math mode. For example, try pasting in Textmate the following three lines:

Now I am in text mode.
$$
Now I am in math mode, but I shouldn't.

I know that the above example wouldn't compile correctly, but there are cases in TeX where two dollar signs might appear.

Thank you for your attention,
Guido

**Comment by sanssecours** [comment]
Hi Guido,

sorry for the late reply. The sample code you mentioned is highlighted correctly as far as I know. The two dollar signs start [display math mode](http://tex.stackexchange.com/questions/40492/what-are-the-differences-between-align-equation-and-displaymath) in a TeX document.

You can test this for yourself. Just translate the following valid LaTeX document:

```tex
\documentclass{article}

\begin{document}

$$Now we are in display math mode.
We are still in display math mode.$$

\end{document}
```

Kind regards,
  René
