### ISSUE TITLE
Article Template?

### ISSUE THREAD

**Issue by ataiya** [textmate/latex.tmbundle#85]
What happened to the Latex article template we used to have in TM1?
It's quite a pain to have to look for one all the time.

**Comment by sanssecours** [comment]
Hi,

commits 3683bde2 and e4e05a7e re-add updated versions of the bundle templates. For quick information on how to use the template system, please take a look at the section “Templates”, on page 11 of the [help document](https://github.com/textmate/latex.tmbundle/blob/master/Support/help/Help.pdf). The help document is also accessible via `Bundles→LaTeX→Help` inside TextMate. 

Kind regards,
  René
